describe('Automated regression suite for the login component of the app', () => {
    it('Verify UI elements on the page ("Login Page" text, "Username" input, "Password" input, "Login" button)', () => {
      cy.visit('https://the-internet.herokuapp.com/login')
      cy.contains('Login Page')
      cy.get('input[id="username"]').should('be.visible')
      cy.get('input[id="password"]').should('be.visible')
      cy.get('button[type="submit"]').should('be.visible')
    })
    it('Verify user is able to login with valid credentials', () => {
        cy.visit('https://the-internet.herokuapp.com/login')
        cy.get('input[id="username"]').type('tomsmith')
        cy.get('input[id="password"]').type('SuperSecretPassword!')
        cy.get('button[type="submit"]').click()
        cy.contains('You logged into a secure area!')
    })
    it('Verify user is able to login on tapping Enter keyboard button (with valid credentials)', () => {
        cy.visit('https://the-internet.herokuapp.com/login')
        cy.get('input[id="username"]').type('tomsmith')
        cy.get('input[id="password"]').type('SuperSecretPassword!')
                                    .type('{enter}')
        cy.contains('You logged into a secure area!')
    })
    it('Verify user is NOT able to login with valid login and INVALID password', () => {
        cy.visit('https://the-internet.herokuapp.com/login')
        cy.get('input[id="username"]').type('tomsmith')
        cy.get('input[id="password"]').type('INVALID_PASSWORD')
        cy.get('button[type="submit"]').click()
        cy.contains('Your password is invalid!')
    })
    it('Verify user is NOT able to login with INVALID login and valid password', () => {
        cy.visit('https://the-internet.herokuapp.com/login')
        cy.get('input[id="username"]').type('INVALID_LOGIN')
        cy.get('input[id="password"]').type('SuperSecretPassword!')
        cy.get('button[type="submit"]').click()
        cy.contains('Your username is invalid!')
    })
    it('Verify user is NOT able to login with valid login and BLANK password', () => {
        cy.visit('https://the-internet.herokuapp.com/login')
        cy.get('input[id="username"]').type('tomsmith')
        cy.get('button[type="submit"]').click()
        cy.contains('Your password is invalid!')
    })
    it('Verify user is NOT able to login with BLANK login and valid password', () => {
        cy.visit('https://the-internet.herokuapp.com/login')
        cy.get('input[id="password"]').type('SuperSecretPassword!')
        cy.get('button[type="submit"]').click()
        cy.contains('Your username is invalid!')
    })
    it('Verify "Logout" button functionality', () => {
        cy.visit('https://the-internet.herokuapp.com/login')
        cy.get('input[id="username"]').type('tomsmith')
        cy.get('input[id="password"]').type('SuperSecretPassword!')
        cy.get('button[type="submit"]').click()
        cy.get('a[href="/logout"]').click()
        cy.contains('You logged out of the secure area!')
    })
    it('Verify clicking "Back" button in the browser does not give user an access to Secure Area', () => {
        cy.visit('https://the-internet.herokuapp.com/login')
        cy.get('input[id="username"]').type('tomsmith')
        cy.get('input[id="password"]').type('SuperSecretPassword!')
        cy.get('button[type="submit"]').click()
        cy.get('a[href="/logout"]').click()
        cy.go('back')
        cy.location('pathname').should('eq', '/login')
    })
  })